version: '3.8'

services:
  backend:
    build: .
    container_name: cms-backend
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cms-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cms_db
    ports:
      - '5432:5432'
