/**
 * Master permission registry for the CMS.
 */
export const PERMISSION_SEED: Record<string, string[]> = {
  assignment: [
    'create',
    'read',
    'read-self',
    'read-all-branches',
    'update',
    'delete',
    'review',
    'submit',
    'manage-global',
  ],
  subject: [
    'create',
    'read',
    'read-all-branches',
    'read-detail',
    'update',
    'delete',
    'manage-global',
  ],
  subject_mapping: [
    'create',
    'read',
    'read-self',
    'read-all-branches',
    'update',
    'delete',
    'manage-global',
  ],
  branch: ['create', 'read', 'update'],
  user: [
    'create',
    'read',
    'read-all-branches',
    'read-detail',
    'update',
    'update-global',
    'delete',
    'manage-role',
    'manage-status',
    'manage-global',
    'manage-permissions', //  V2 Phase 3: Power to grant/revoke overrides
    'read-logs', //  V2 Phase 5: Power to view audit logs

    //  NEW UI PERMISSIONS ADDED HERE
    'filter-branch',
    'manage-staff',
    'manage-students',
  ],

  //  NEW STUDENT RESOURCE ADDED HERE
  student: ['create', 'read', 'update', 'delete'],

  profile: ['read', 'update', 'update-image'],
  staff: ['create', 'read', 'update'],
  file: ['upload', 'delete'],
  auth: ['register-staff'],
  settings: ['read', 'update'],
  role: ['create', 'read', 'update', 'delete'],
  permission: ['read'],
  study_material: ['create', 'read', 'update', 'delete'],
};

export const ROLE_PERMISSION_SEED: Record<string, string[]> = {
  SUPER_ADMIN: ['*:*'],
  PENDING_USER: [
    'profile:read',
    'profile:update',
    'file:upload',
    'profile:update-image',
  ],
  HOD: [
    'assignment:create',
    'assignment:read',
    'assignment:read-self',
    'assignment:update',
    'assignment:delete',
    'assignment:review',
    'subject:create',
    'subject:read',
    'subject:update',
    'subject:delete',
    'subject:assign',
    'subject:unassign',
    'subject-mapping:create',
    'subject_mapping:create',
    'subject_mapping:read',
    'subject_mapping:update',
    'subject_mapping:delete',
    'user:create',
    'user:read',
    'user:update',
    'user:manage-role',
    'user:manage-status',
    'user:manage-permissions',
    'user:read-logs',
    'staff:create',
    'staff:read',
    'staff:update',

    //  NEW HOD DELEGATED PERMISSIONS ADDED HERE
    'user:manage-staff',
    'user:manage-students',
    'student:read',

    'profile:read',
    'profile:update',
    'profile:update-image',
    'file:upload',
    'file:delete',
    'auth:register-staff',
    'settings:read',
    'settings:update',
    'branch:read',
    'role:read',
  ],
  PROFESSOR: [
    'assignment:create',
    'assignment:read-self',
    'assignment:read',
    'assignment:update',
    'assignment:delete',
    'assignment:review',
    'subject:read',
    'subject_mapping:read',
    'user:read',
    'profile:read',
    'profile:update',
    'profile:update-image',
    'staff:read',
    'file:upload',
    'file:delete',
    'settings:read',
    'study_material:create',
    'study_material:read',
    'study_material:update',
    'study_material:delete',
  ],
  STUDENT: [
    'assignment:read',
    'assignment:submit',
    'subject:read',
    'user:read',
    'profile:read',
    'profile:update',
    'profile:update-image',
    'file:upload',
    'settings:read',
    'study_material:read',
  ],
  LIBRARIAN: [],
};

export const ROLE_DESCRIPTIONS: Record<string, string> = {
  SUPER_ADMIN: 'Full system access with wildcard permissions',
  HOD: 'Head of Department — manages branch-level operations and delegates permissions',
  PROFESSOR: 'Faculty member — manages assignments and study materials',
  STUDENT: 'Student — submits assignments, views materials',
  LIBRARIAN: 'Library staff — manages library resources',
  PENDING_USER: 'Newly registered user awaiting Admin approval',
};
