export const ENUM_TYPES = {
  ROLE: 'USER_ROLE',
  SEMESTER: 'SEMESTER',
  GENDER: 'GENDER',
  USER_ACC_STATUS: 'USER_ACCOUNT_STATUS',
};

export const ENUM_VALUES = {
  USER_ACC_STATUS: {
    ACTIVE: 'ACTIVE',
    PENDING: 'PENDING',
    BLOCKED: 'BLOCKED',
    REJECTED: 'REJECTED',
    INACTIVE: 'INACTIVE',
    GRADUATED: 'GRADUATED',
  },
};
