export const ROUTENAME = {
  SIGNIN: "/signin",
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  VERIFY_EMAIL: "/profile/verify-email",
  RESET_PASSWORD: "/profile/reset-password",
  AUTH_RESET_PASSWORD: `/reset-password`,
  SUBJECTS: "/subjects",
  ADD_SUBJECT: "/subjects/register",
  SUBJECT_DETAILS: `/subject/:id`,
  ASSIGN_SUBJECT: "/assign-subject",
  ASSIGNMENT: "/assignments",
  ADD_ASSIGNMENT: "/assignment/create",
  MY_ASSIGNMENT: "/assignments/me",
  EDIT_ASSIGNMENT: "/update/:id",
  VIEW_ASSIGNMENT: "/assignments/:id",
  BRANCH: "/branch",
  ADD_BRANCH: "/branch/register",
  ALL_USERS: "/users",
  USER_DETAILS: `/user/:id`,
  ADD_STAFF: "/user/create",
  // SETTING: "/setting",
  // V2: Account status pages
  SUSPENDED: "/account/suspended",
  EMAIL_REQUEST: "/verify-email",

  SETTING: "/settings",
  ENUMS: "/settings/constants",
} as const;
