export const ROUTENAME = {
  SIGNIN: "/signin",
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  VERIFY_EMAIL: "/profile/verify-email",
  RESET_PASSWORD: "/profile/reset-password",
  AUTH_RESET_PASSWORD: `/reset-password`,
  SUBJECTS: "/subjects",
  ADD_SUBJECT: "/subjects/register",
  PROFESSOR_ASSIGN_SUBJECT_POST: "/assign-subject",
  PROFESSOR_ASSIGNED_SUBJECT_GET: "/professor-subject",
  ASSIGNMENT: "/assignments",
  ADD_ASSIGNMENT: "/assignment/register",
  MY_ASSIGNMENT: "/assignments/me",
  BRANCH: "/branch",
  ADD_BRANCH: "/branch/register",
  ALL_USERS: "/users/all",
  ADD_HOD: "/register/hod",
  ADD_PROFESSOR: "/register/professor",
  ALL_PROFESSOR: "/professors",
  ALL_STUDENT: "/studentS",
} as const;
