export const ROUTENAME = {
  SIGNIN: "/signin",
  LOGIN: "/login",
  FORGET_PASSWORD: "/forgot-password",
  DASHBOARD: "/dashboard",
  PROFILE: "/profile",
  VERIFY_EMAIL: "/profile/verify-email",
  RESET_PASSWORD: "/profile/reset-password",
  AUTH_RESET_PASSWORD: `/reset-password`,
  SUBJECTS: "/subjects",
  ADD_SUBJECT: "/subjects/register",
  SUBJECT_DETAILS: `/subject/:id`,
  PROFESSOR_ASSIGN_SUBJECT_POST: "/assign-subject",
  PROFESSOR_ASSIGNED_SUBJECT_GET: "/professor-subject",
  ASSIGNMENT: "/assignments",
  ADD_ASSIGNMENT: "/assignment/register",
  MY_ASSIGNMENT: "/assignments/me",
  BRANCH: "/branch",
  ADD_BRANCH: "/branch/register",
  ALL_USERS: "/users",
  USER_DETAILS: `/user/:id`,
  ADD_STAFF: "/user/create",
} as const;
